repos:
  - repo: https://github.com/psf/black
    rev: 24.9b0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 0.12.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
